# Prayer Time Scheduler

The purpose of this notebook is to add to Google Calendar the iqamah time at the local masjid (for me: ISBCC).

## Constants

In [2]:
# website
# https://timing.athanplus.com/masjid/widgets/monthly?masjid_id=zVKp9PLP

MASJID_ID: str = "zVKp9PLP"
GMAIL_ADDRESS: str = "awab.masroor@gmail.com"
URL: str = f"https://timing.athanplus.com/masjid/widgets/monthly?masjid_id={MASJID_ID}"
MONTH: str = "APRIL"
MASJID: str = "ISBCC"

In [3]:
PRAYER_TIMES: set = {
    "FAJR",
    "DHUHR",
    "ASR",
    "MAGHRIB",
    "ISHA",
}

### Install Dependencies

In [4]:
%pip install requests beautifulsoup4 pandas datetime
%pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (4.13.3)
Requirement already satisfied: pandas in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.2.3)
Requirement already satisfied: datetime in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (5.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests) (2025.1.31)
Requirement already satisfied: soupsieve>1.2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from beautifulsoup4) (4.12.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: zope.interface in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from datetime) (7.2)
Requirement already satisfied: six>=1.5 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from zope.interface->datetime) (75.8.2)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: google-api-python-client in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.162.0)
Collecting google-api-python-client
  Downloading google_api_python_client-2.166.0-py2.py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: google-auth-httplib2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.2.0)
Requirement already satisfied: google-auth-oauthlib in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.2.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-python-client) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-python-client) (2.38.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-python-client) (2.24.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-python-client) (4.1.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-auth-oauthlib) (2.0.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.68.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.26.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.2.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abmas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2025.1.31)
Downloading google_api_python_client-2.166.0-py2.py3-none-any.whl (13.2 MB)
   ---------------------------------------- 0.0/13.2 MB ? eta -:--:--
   ------------------------ --------------- 8.1/13.2 MB 45.7 MB/s eta 0:00:01
   ---------------------------------------- 13.2/13.2 MB 45.8 MB/s eta 0:00:00
Installing collected packages: google-api-python-client
  Attempting uninstall: google-api-python-client
    Found existing installation: google-api-python-client 2.162.0
    Uninstalling google-api-python-client-2.162.0:
      Successfully uninstalled google-api-python-client-2.162.0
Successfully installed google-api-python-client-2.166.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\abmas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Code

In [5]:
# get website
import requests
response = requests.get(URL)

if response.status_code == 200:
    print("Success")
else: 
    print("Failure")

Success

In [6]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# get the table
table = soup.find_all(id="time-table3")[0]
table

<table id="time-table3">
<!--table class="full-table-sec full-table-sec2"-->
<tr>
<td class="subHeader">
                                            APRIL
                                    </td>
<td class="subHeader">
                                            SHAWWAL
                                    </td>
<td class="subHeader">
                                            FAJR
                                    </td>
<td class="subHeader">
                                            SUNRISE
                                    </td>
<td class="subHeader">
                                            DHUHR
                                    </td>
<td class="subHeader">
                                            ASR
                                    </td>
<td class="subHeader">
                                            MAGHRIB
                                    </td>
<td class="subHeader">
                                            ISHA
                                    </td>
</tr>
<tr>
<td class="regCell">
<span>1, TUE</span></td>
<td class="regCell">
<span>    3</span></td>
<td class="regCell">
<span>5:06  |
                                                                                    5:30

                                            </span></td>
<td class="regCell">
<span>6:26 </span></td>
<td class="regCell">
<span>12:48  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:24  |
                                                                                    4:35
                                        </span></td>
<td class="regCell">
<span>7:12  | 7:18 </span></td>
<td class="regCell">
<span>8:31  |
                                                                                    8:45
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>2, WED</span></td>
<td class="regCell">
<span>    4</span></td>
<td class="regCell">
<span>5:04  |
                                                                                    5:30

                                            </span></td>
<td class="regCell">
<span>6:25 </span></td>
<td class="regCell">
<span>12:48  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:25  |
                                                                                    4:35
                                        </span></td>
<td class="regCell">
<span>7:13  | 7:19 </span></td>
<td class="regCell">
<span>8:32  |
                                                                                    8:45
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>3, THU</span></td>
<td class="regCell">
<span>    5</span></td>
<td class="regCell">
<span>5:02  |
                                                                                    5:30

                                            </span></td>
<td class="regCell">
<span>6:23 </span></td>
<td class="regCell">
<span>12:48  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:25  |
                                                                                    4:35
                                        </span></td>
<td class="regCell">
<span>7:14  | 7:20 </span></td>
<td class="regCell">
<span>8:34  |
                                                                                    8:45
                                        </span></td>
</tr>
<tr>
<td class="regCell friday">
<span>4, FRI</span></td>
<td class="regCell friday">
<span>    6</span></td>
<td class="regCell friday">
<span>5:01  |
                                                                                    5:30

                                            </span></td>
<td class="regCell friday">
<span>6:21 </span></td>
<td class="regCell friday">
<span>12:47  |
                                                                                    1:00
                                        </span></td>
<td class="regCell friday">
<span>4:25  |
                                                                                    4:35
                                        </span></td>
<td class="regCell friday">
<span>7:15  | 7:21 </span></td>
<td class="regCell friday">
<span>8:35  |
                                                                                    8:45
                                        </span></td>
</tr>

<tr>
<td class="regCell">
<span>5, SAT</span></td>
<td class="regCell">
<span>    7</span></td>
<td class="regCell">
<span>4:59  |

                                            <b>5:15 </b>
</span></td>
<td class="regCell">
<span>6:20 </span></td>
<td class="regCell">
<span>12:47  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:26  |

                                            <b>4:40 </b>
</span></td>
<td class="regCell">
<span>7:16  | 7:21 </span></td>
<td class="regCell">
<span>8:36  |

                                            <b>8:50 </b>
</span></td>
</tr>
<tr>
<td class="regCell">
<span>6, SUN</span></td>
<td class="regCell">
<span>    8</span></td>
<td class="regCell">
<span>4:57  |
                                                                                    5:15

                                            </span></td>
<td class="regCell">
<span>6:18 </span></td>
<td class="regCell">
<span>12:47  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:26  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:17  | 7:22 </span></td>
<td class="regCell">
<span>8:38  |
                                                                                    8:50
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>7, MON</span></td>
<td class="regCell">
<span>    9</span></td>
<td class="regCell">
<span>4:55  |
                                                                                    5:15

                                            </span></td>
<td class="regCell">
<span>6:16 </span></td>
<td class="regCell">
<span>12:46  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:27  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:18  | 7:23 </span></td>
<td class="regCell">
<span>8:39  |
                                                                                    8:50
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>8, TUE</span></td>
<td class="regCell">
<span>    10</span></td>
<td class="regCell">
<span>4:53  |
                                                                                    5:15

                                            </span></td>
<td class="regCell">
<span>6:14 </span></td>
<td class="regCell">
<span>12:46  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:27  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:19  | 7:24 </span></td>
<td class="regCell">
<span>8:40  |
                                                                                    8:50
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>9, WED</span></td>
<td class="regCell">
<span>    11</span></td>
<td class="regCell">
<span>4:51  |
                                                                                    5:15

                                            </span></td>
<td class="regCell">
<span>6:13 </span></td>
<td class="regCell">
<span>12:46  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:28  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:21  | 7:26 </span></td>
<td class="regCell">
<span>8:42  |
                                                                                    8:50
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>10, THU</span></td>
<td class="regCell">
<span>    12</span></td>
<td class="regCell">
<span>4:49  |
                                                                                    5:15

                                            </span></td>
<td class="regCell">
<span>6:11 </span></td>
<td class="regCell">
<span>12:46  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:28  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:22  | 7:27 </span></td>
<td class="regCell">
<span>8:43  |
                                                                                    8:50
                                        </span></td>
</tr>
<tr>
<td class="regCell friday">
<span>11, FRI</span></td>
<td class="regCell friday">
<span>    13</span></td>
<td class="regCell friday">
<span>4:47  |
                                                                                    5:15

                                            </span></td>
<td class="regCell friday">
<span>6:09 </span></td>
<td class="regCell friday">
<span>12:45  |
                                                                                    1:00
                                        </span></td>
<td class="regCell friday">
<span>4:28  |
                                                                                    4:40
                                        </span></td>
<td class="regCell friday">
<span>7:23  | 7:28 </span></td>
<td class="regCell friday">
<span>8:44  |
                                                                                    8:50
                                        </span></td>
</tr>

<tr>
<td class="regCell">
<span>12, SAT</span></td>
<td class="regCell">
<span>    14</span></td>
<td class="regCell">
<span>4:45  |

                                            <b>5:00 </b>
</span></td>
<td class="regCell">
<span>6:08 </span></td>
<td class="regCell">
<span>12:45  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:29  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:24  | 7:29 </span></td>
<td class="regCell">
<span>8:46  |

                                            <b>9:00 </b>
</span></td>
</tr>
<tr>
<td class="regCell">
<span>13, SUN</span></td>
<td class="regCell">
<span>    15</span></td>
<td class="regCell">
<span>4:43  |
                                                                                    5:00

                                            </span></td>
<td class="regCell">
<span>6:06 </span></td>
<td class="regCell">
<span>12:45  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:29  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:25  | 7:30 </span></td>
<td class="regCell">
<span>8:47  |
                                                                                    9:00
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>14, MON</span></td>
<td class="regCell">
<span>    16</span></td>
<td class="regCell">
<span>4:41  |
                                                                                    5:00

                                            </span></td>
<td class="regCell">
<span>6:05 </span></td>
<td class="regCell">
<span>12:45  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:30  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:26  | 7:31 </span></td>
<td class="regCell">
<span>8:49  |
                                                                                    9:00
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>15, TUE</span></td>
<td class="regCell">
<span>    17</span></td>
<td class="regCell">
<span>4:39  |
                                                                                    5:00

                                            </span></td>
<td class="regCell">
<span>6:03 </span></td>
<td class="regCell">
<span>12:44  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:30  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:27  | 7:32 </span></td>
<td class="regCell">
<span>8:50  |
                                                                                    9:00
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>16, WED</span></td>
<td class="regCell">
<span>    18</span></td>
<td class="regCell">
<span>4:38  |
                                                                                    5:00

                                            </span></td>
<td class="regCell">
<span>6:01 </span></td>
<td class="regCell">
<span>12:44  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:30  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:28  | 7:33 </span></td>
<td class="regCell">
<span>8:52  |
                                                                                    9:00
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>17, THU</span></td>
<td class="regCell">
<span>    19</span></td>
<td class="regCell">
<span>4:36  |
                                                                                    5:00

                                            </span></td>
<td class="regCell">
<span>6:00 </span></td>
<td class="regCell">
<span>12:44  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:31  |
                                                                                    4:40
                                        </span></td>
<td class="regCell">
<span>7:30  | 7:35 </span></td>
<td class="regCell">
<span>8:53  |
                                                                                    9:00
                                        </span></td>
</tr>
<tr>
<td class="regCell friday">
<span>18, FRI</span></td>
<td class="regCell friday">
<span>    20</span></td>
<td class="regCell friday">
<span>4:34  |
                                                                                    5:00

                                            </span></td>
<td class="regCell friday">
<span>5:58 </span></td>
<td class="regCell friday">
<span>12:44  |
                                                                                    1:00
                                        </span></td>
<td class="regCell friday">
<span>4:31  |
                                                                                    4:40
                                        </span></td>
<td class="regCell friday">
<span>7:31  | 7:36 </span></td>
<td class="regCell friday">
<span>8:54  |
                                                                                    9:00
                                        </span></td>
</tr>

<tr>
<td class="regCell">
<span>19, SAT</span></td>
<td class="regCell">
<span>    21</span></td>
<td class="regCell">
<span>4:32  |

                                            <b>4:50 </b>
</span></td>
<td class="regCell">
<span>5:57 </span></td>
<td class="regCell">
<span>12:43  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:32  |

                                            <b>4:45 </b>
</span></td>
<td class="regCell">
<span>7:32  | 7:37 </span></td>
<td class="regCell">
<span>8:56  |

                                            <b>9:10 </b>
</span></td>
</tr>
<tr>
<td class="regCell">
<span>20, SUN</span></td>
<td class="regCell">
<span>    22</span></td>
<td class="regCell">
<span>4:30  |
                                                                                    4:50

                                            </span></td>
<td class="regCell">
<span>5:55 </span></td>
<td class="regCell">
<span>12:43  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:32  |
                                                                                    4:45
                                        </span></td>
<td class="regCell">
<span>7:33  | 7:38 </span></td>
<td class="regCell">
<span>8:57  |
                                                                                    9:10
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>21, MON</span></td>
<td class="regCell">
<span>    23</span></td>
<td class="regCell">
<span>4:28  |
                                                                                    4:50

                                            </span></td>
<td class="regCell">
<span>5:54 </span></td>
<td class="regCell">
<span>12:43  |
                                                                                    1:00
                                        </span></td>
<td class="regCell">
<span>4:32  |
                                                                                    4:45
                                        </span></td>
<td class="regCell">
<span>7:34  | 7:39 </span></td>
<td class="regCell">
<span>8:59  |
                                                                                    9:10
                                        </span></td>
</tr>
<tr>
<td class="regCell">
<span>22, TUE</span></td>
<td class="regCell">
<span>    24</span></td>
<td class="regCell">
<span>4:26  |

In [7]:
# get the headers (class = subHeader)
headers = table.find_all(class_="subHeader")
headers = [header.text.strip() for header in headers]
headers

['APRIL', 'SHAWWAL', 'FAJR', 'SUNRISE', 'DHUHR', 'ASR', 'MAGHRIB', 'ISHA']

In [8]:
# get the rows
rows = []
for tr in table.find_all('tr')[1:]:  # Skip the header row
    cols = tr.find_all('td')
    row = [col.get_text().strip() for col in cols]
    rows.append(row)

rows[0]

['1, TUE',
 '3',
 '5:06  |  \r\n                                                                                    5:30',
 '6:26',
 '12:48  | \r\n                                                                                    1:00',
 '4:24  | \r\n                                                                                    4:35',
 '7:12  | 7:18',
 '8:31  |  \r\n                                                                                    8:45']

In [9]:
import pandas as pd
df = pd.DataFrame(rows, columns=headers)

In [10]:
# get the dates
from datetime import datetime
dates = []
for index, row in df.iterrows():    
    # get date
    month = MONTH
    day = row[MONTH]
    year = datetime.now().year
    # parse the number of the day
    day = int(day.split()[0].replace(',', ''))
    date = datetime.strptime(f"{year} {month} {day}", "%Y %B %d")
    
    dates.append(date)

In [11]:
new_df = pd.DataFrame(dates, columns=["Date"])

In [12]:
for prayer in PRAYER_TIMES:
    new_df[f"{prayer} Adhan"] = df[prayer].apply(lambda x: x.split()[0])
    new_df[f"{prayer} Iqamah"] = df[prayer].apply(lambda x: x.split()[2])

# remove the old columns
new_df.head(10)

,Date,MAGHRIB Adhan,MAGHRIB Iqamah,ASR Adhan,ASR Iqamah,DHUHR Adhan,DHUHR Iqamah,ISHA Adhan,ISHA Iqamah,FAJR Adhan,FAJR Iqamah
0,2025-04-01,7:12,7:18,4:24,4:35,12:48,1:00,8:31,8:45,5:06,5:30
1,2025-04-02,7:13,7:19,4:25,4:35,12:48,1:00,8:32,8:45,5:04,5:30
2,2025-04-03,7:14,7:20,4:25,4:35,12:48,1:00,8:34,8:45,5:02,5:30
3,2025-04-04,7:15,7:21,4:25,4:35,12:47,1:00,8:35,8:45,5:01,5:30
4,2025-04-05,7:16,7:21,4:26,4:40,12:47,1:00,8:36,8:50,4:59,5:15
5,2025-04-06,7:17,7:22,4:26,4:40,12:47,1:00,8:38,8:50,4:57,5:15
6,2025-04-07,7:18,7:23,4:27,4:40,12:46,1:00,8:39,8:50,4:55,5:15
7,2025-04-08,7:19,7:24,4:27,4:40,12:46,1:00,8:40,8:50,4:53,5:15
8,2025-04-09,7:21,7:26,4:28,4:40,12:46,1:00,8:42,8:50,4:51,5:15
9,2025-04-10,7:22,7:27,4:28,4:40,12:46,1:00,8:43,8:50,4:49,5:15

In [13]:
from datetime import timedelta

date_df_data = []

# go through the rows and create events
for index, row in new_df.iterrows():
    new_row = {}
    new_row['Date'] = row['Date']
        
    for col in new_df.columns.drop('Date'):
        if ("DHUHR" in col or "ASR" in col or "MAGHRIB" in col or "ISHA" in col) and "11:" not in row[col]:
            dt = datetime.combine(row['Date'], datetime.strptime(f'{row[col]}', "%I:%M").time())
            dt = dt + timedelta(hours=12)
        else:
            dt = datetime.combine(row['Date'], datetime.strptime(row[col], "%H:%M").time())
        
        new_row[col] = dt

    date_df_data.append(new_row)

date_df = pd.DataFrame(date_df_data)

In [ ]:
# grab google credentials
import os.path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

creds = None
SCOPES = ['https://www.googleapis.com/auth/calendar']

if os.path.exists('token.json'):
    if (datetime.now() - datetime.fromtimestamp(os.path.getmtime('token.json'))) > timedelta(hours=24):
        print("The creds file is over 24 hours old. Deleting creds")
        os.remove('token.json')
    else:
        creds = Credentials.from_authorized_user_file('token.json')

# If there are no (valid) credentials available, let the user log in.
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'credentials.json', SCOPES)
        creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open('token.json', 'w') as token:
        token.write(creds.to_json())

service = build('calendar', 'v3', credentials=creds)

The creds file is over 24 hours old. Deleting creds
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=380996284341-ql71lc3fj2ini29vfs0cf84ffd131gev.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A50347%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&state=yv1fFoyN9dTyQfqdj3f806JmJe61XP&access_type=offline

In [24]:

from datetime import datetime, timedelta

def create_event(summary: str, location: str, start: datetime, end: datetime, description: str, reminders: list):
    event = {
        'summary': summary,
        'location': location,
        'description': description,
        'start': {
            'dateTime': start.strftime("%Y-%m-%dT%H:%M:%S"),
            'timeZone': 'America/New_York',
        },
        'end': {
            'dateTime': end.strftime("%Y-%m-%dT%H:%M:%S"),
            'timeZone': 'America/New_York',
        },
        'reminders': {
            'useDefault': False,
            'overrides': reminders
        },
    }

    event = service.events().insert(calendarId='60926a588d0fee35fdeaa1efde65cdcf9d6d85e2601396a18461687ea38aadf5@group.calendar.google.com', body=event).execute()
    print('Event created: %s' % (event.get('htmlLink')))

# create_event('Fajr Salah', 'https://maps.app.goo.gl
# /kC7nVr2kWGn4pNV96', datetime.now() + timedelta(days=1),
# datetime.now() + timedelta(days=1, minutes=10), 'Fajr Salah',
# [{'method': 'popup', 'minutes': 30}, {'method': 'popup', 'minutes': 15}])

In [25]:
date_df.head(3)

,Date,MAGHRIB Adhan,MAGHRIB Iqamah,ASR Adhan,ASR Iqamah,DHUHR Adhan,DHUHR Iqamah,ISHA Adhan,ISHA Iqamah,FAJR Adhan,FAJR Iqamah
0,2025-04-01,2025-04-01 19:12:00,2025-04-01 19:18:00,2025-04-01 16:24:00,2025-04-01 16:35:00,2025-04-01 12:48:00,2025-04-01 13:00:00,2025-04-01 20:31:00,2025-04-01 20:45:00,2025-04-01 05:06:00,2025-04-01 05:30:00
1,2025-04-02,2025-04-02 19:13:00,2025-04-02 19:19:00,2025-04-02 16:25:00,2025-04-02 16:35:00,2025-04-02 12:48:00,2025-04-02 13:00:00,2025-04-02 20:32:00,2025-04-02 20:45:00,2025-04-02 05:04:00,2025-04-02 05:30:00
2,2025-04-03,2025-04-03 19:14:00,2025-04-03 19:20:00,2025-04-03 16:25:00,2025-04-03 16:35:00,2025-04-03 12:48:00,2025-04-03 13:00:00,2025-04-03 20:34:00,2025-04-03 20:45:00,2025-04-03 05:02:00,2025-04-03 05:30:00

In [26]:
# go through the rows and create events
for index, row in date_df.iterrows():
    for prayer in PRAYER_TIMES:
        prayer_name = prayer.title()
        summary = f"{prayer_name} Salah"
        location = "https://maps.app.goo.gl/kC7nVr2kWGn4pNV96"
        start = row[prayer + " Iqamah"]
        end = row[prayer + " Iqamah"] + timedelta(minutes=10)
        description = f"{prayer_name} Salah at {MASJID}"
        reminders = [{'method': 'popup', 'minutes': 30}, {'method': 'popup', 'minutes': 15}]

        create_event(summary, location, start, end, description, reminders)

Event created: https://www.google.com/calendar/event?eid=cjIydjcxOWhnazJmbGVobmphZWY5dTJvNzAgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZzRoYmFxcjM5MjNldmR0Y3A2NWpvcjMzdGsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZHZsMGVhMmYwYmQ5NzZ0cm0wNzM3dTNxMzggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cWN1bzZuZDJyYjdyMjZxdWw0cjUyazliOTAgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bmk1NzBpbGR2NGMwNjN1c3UzNnNjY2JmcDQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cGpxbzA5NjVlM2N0NW44OWl2cGdrdWFuOGcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NWFkNm1zYmhoMm1ncGQyb3AwcjhndjQ2Zm8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bzVpOWgybG1rcWRnOTlsOWY0N2QydG8waGcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bW41ajBjNzAxamptdjE0dGtyYXZlcDduNTAgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cHYxaDltMG12c2wzamRxMmI0Z2JmdXZjN28gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=c2NkMHJsMm5oNG1obTF2YWI3Z3V0dms1NzggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dGJlZGFmbW9wYzh2b3Q1YmU1OTJsYXRkMmsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=M2dvMmVkbDZka3V1a3BucnFmcjFoYmgyczQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Z3RraGdpMnJqMWt1ZHJ2MjFnaDRxMzY1N2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=aHJmdnRwbm9hMWUyZ2M4aHVwanA0cjc0cW8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NTI0Y2d0bHQyMm80ZzY3cjk4NWkxa3ExMHMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Y3NnbHJqbGlnczNxYjl2OHU1bzI1cHN2c2MgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cjIzbnY0MGc0NTUwZW9vaHBtcG1mZXUwOGMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MXAyYjVxOTIxMDNtcXY5cXJiNnNoZ2FrYWsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dXNtZmc2b3FhamQyMm9lbDdodW5jaHZ0dTQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=YnI5NjMxcHUwZG11MWFlOG1yMGl1aDNyZ2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bDNodWtzczJwOWt2dWpjbXE5dnM4YTlybGsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cWJhMmJhNW45M3NtMjFhZGF2ODE3cWVkYXMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=M2VqNXBrYmJ0bGYwbDQzNzdhZmwzcnFrNzggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cDh0c3VhZDZxdGVlY3ZvMTZ0NjIwMjBlcGMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Mjhzb2E1bDhsMmE5YTE1MmdpbG43bjFqcm8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=N2J1dnE2MDU2cWo0OWZ0OTI5MTVxajEwN2MgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZDVqcTlpOWJqM3M4ZTY5Z2RpczdhOHFrNW8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cnAyaGNvMm9qdmgzOG1wMjFhcmxnZmI4NWcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZW9yZzVuZmUybGM3NjE3dDAwaTNrb2J0dnMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cDFwOWppNDk1dWc4N29tOXJ1ZW83c2ZqZWsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MWs1Z2g0cDhvMml1NjRwbzA2MzNnOWdzY2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MGQyOWx2ZmhhczZpMGQ4dGRlZjh0aTVnaW8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dm9iZHZicG5yMmdmbGYwMWhsbHFmajVxNG8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MWE4NDIyczZhMzYyOW85YWVqaTFrc28wbmsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=b3VydmVpdXVmbjRuN3Bja2EwZTZnczRsNzggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=c2M4dWM1b2FzMHUzNmhwNXVxZXRsZmp2cGcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=b2ExZG1nMzh1NXNhaGw5Zmhnc3NvNzRpaXMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bTMycmprcWN0bm1jZ3RmMWpxMzg2NXI4bmMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=b3BqbmFpcGM2dnQyaDg2bXQxYmltMjM1OWsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=czZkYWZkb2NiM2M1N2hwcWJkcDRlamNkOHMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=OWQ1NmZtNThyM2Vka3RxcTgxcXBlaWQ5a2sgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Ymc1bXMzM3NpaWw1bzVybmhqOTk3NTZla28gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bzZvcXVjcGRwdm11dHE1b25kNnFhb3ZyYW8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cjNsNG05a2J0OGEydjg2NWNxbzRnZzEwNGcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NG01dTg2ZGIwa3VoZzVjZnVxcm4zNG1lZHMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MTVwdDRvNmhmaHZpOThqaGNpb3JsMDU3YmcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NWRkbnZpdTdubHYzNGg1cXU3ZjlrY2VqNWsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=aWVyODFrdnFqcGk4cDFvNHIxaTJsanVmMW8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cTVuZXZhY3M2bDlmYTNjdWlqMzVqdW1xZjggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=b3JhMHBrZTFnbWQ5Zm52bm1oOTVxdmE4a28gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MzFiN2dtbzE5N3M2ajQxbGwzaTMxOWJsMjggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bmRwc2N2MTBrMW5nNTJzdm1ra2l0ZDNhbDQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Y2gxbWczM3Y1bmlncTh0NTZoODg3MDBqMTAgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=N3NnbTV1cmJyMXRxcHUxY2cxdTVzamtvdmcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Z2lhYW80cmgxZ3ZkN2xlaDRmNTliNzRwYXMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Z29xZXYxOTdkaDByc3BmbGYyam50dGFqbDggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=N2x2aDA0dTl2dmNwbnIxMTU0ODBnNzFmZ28gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZTJhbnI3ajkxdXNtcnE5bGYzbGlibGQ0dmMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=azgyY3JldGoybjE4Z2FuZGhlbXZkcDZvcTggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cDVoNm5vajg5b2M2ZWh2anAycnMycmh0M2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=M20xbDBjdDFmdG5zNnYzcHYycnA1Y3BucXMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=a2ZxaWdmM2JmaHY0OW04NTVrcnVpZDExMGMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cTRzaHNnOTZhcTRhajB1YzJucTg2bWlyY2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ajEzaXBqdXVtM2NpNWF0MWZlMm5lb3V0OTQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Z3NxYmhidjR2ZHYxMjlnbG1hNXZuN2JjNGsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=aWsxOTdubHE5ZjFzNTU1YmJyY2hrdDdxcGMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cXU4NDZmaGk0Z285bnBwNHBlbmh2bjE3c28gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=c2d2YTk4MWIwdjZpcG85Ym44b2hvdXNnMjggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=a2Z0YWprZXVhYmkwdjBoZGk1YWE5MXAxaDggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZDFudGRwNXE5MTdmbmszcHE1NzNnNHRqMDggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MG5oZDYyMHBwdGJobWVrNXY3Nzk3ajFrcG8gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dTd0cHF1cnJhOGZvbjJocXZlbXBjNDJwaDggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MzllbWM4cXMyMGozMGs3aGVkNzQxaXUycTQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=b2Y2YjA3YTNlczVrZjNiaGFnZ3ZtbzFibjggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=OGdmZXFpcmZtZTNoaTFtY21pY29sODhnY3MgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZGJucXFvOGQ2bGE5N29ncDY3MmtkaDR1OHMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZDBnNTdhbWUyMzdrYzRyYmUxODgyYmVvaDQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NTZucDY4dHVuNjZiZ3FrbDNwZjF0NmhtMDAgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cm5lZnJxNjgxcXNxOXQ1dnVkdG1wOGVqbGcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dTJxYmZuOTNnaG50cDhzbzIyZDRub25ldGcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bmM5cDhlZDcyaWQyOTBwdmVwcjJ1ODdsaTQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=aWlwZGZ1MXJlNWVxMW44YWk2aGNpdDMycTggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=aTlobjVidWF0aGpqZ2FoZTAybGt1Y3FpODggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=aDdjc3Q5YjhjZnVvMTYycGQ1Ym5kcjg4aTggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=YTBwaHJ1aDYxaDgxM3VnNXZpMWVrdmYwdWsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=YnIxdGNocDFwNzNtMWh0ajIzOWdqdmdna2sgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=azBuNzJqdnVkbGg3azdzaHZjYTlvb3FpNzAgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Mms5dGU1cWI5OG9qc2NqbXBwbHM1czZvaXMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZDBmNm80N292a3ZtNzA4MnJkM3A2OTdqazggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=b3BjMWU2bGlrNjBnbXVkZzNvbTlya2M1MHMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=MzFlaHRuZ201amVkMmVwbDlnZWp1a2FlMTggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dDlxaHVsM240MWVjZDF1bDBxZmRtN2wwMmcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dnI3c29jNTFhY3BnaXJobTM4dGhhOXB1ZWcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cnRuZDFmYnNhZXU5NGNqZDQxcmliYTdpY28gNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=cHVvMXZhaTZlcGZmdHNqa25xb2VuaGg0Y2MgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NWNxZ2QwanR1ZTMxYTBybzQ0bG9rdWFoOWsgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bDVnbmkxbHZlMmEyb29wZm52cmN2aDRlbXMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=a2k3N2d0cmo0dHFjdWtkdWM0bWRlOHJjc2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=dWZwc2dkbTg3bDBwYjRzMWd2YjVzb3EwN2cgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=czYwMDI2NW5jZWdobXA5M243cmhobDdoMDQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=bWZlcnNybjMxMmdjNXRiMGZkOGszajEwZDQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=Y3RqMDhhM21xaGc1c2tjc2p1NmY2MXBic3MgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NG5jMHN0N3JsZzYzMzRoOGhtcnJkbmNyNDggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=ZWg1NGlnMnM2M3J1NGptamJvdXFicG1lbDQgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NGhjbXFyaWo2aG5hb2NpcjRvbDQ1dmNzdmMgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=YjYxZWE2MmtyZWp2NWhzaHVoMWQ4Mmd1NWcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=NjFmODlibmtibmsxN25wM2lsNnF2ZjRoamcgNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn
Event created: https://www.google.com/calendar/event?eid=OXJsMGtrNGd0Z3Fzcm1hZ2RzOTFyMm0wYTggNjA5MjZhNTg4ZDBmZWUzNWZkZWFhMWVmZGU2NWNkY2Y5ZDZkODVlMjYwMTM5NmExODQ2MTY4N2VhMzhhYWRmNUBn